### ISSUE TITLE
Integration not working after upgrading HA to 0.111.0

### ISSUE THREAD

**Issue by GitHubxtsnl** [Sholofly/ZiggoNext#28]
running
HA 0.111.0
HASSOS 4.10
on Pi4

after upgrading to HA 0.110.0 the ziggonext integration reports "The following integrations and platforms could not be set up".

below the snippet of my configuration.yaml.

```
# ZIGGO NEXT MEDIABOX INTEGRATION - ! PLEASE SET ENERGY MODE ON NEXT BOX TO "hoog"
ziggonext:
  username: !secret ziggo_username
  password: !secret ziggo_password
```
