### ISSUE TITLE
Exit Netflix or Videoland (more control of mediabox)

### ISSUE THREAD

**Issue by davidrustingha** [Sholofly/ZiggoNext#37]
First of all, thanks for all the hard work. The integration works like a charm!

Would it be possible to be able to have more control of the mediabox, for example:

- When I launch Netflix, I am not able to launch Videoland while i'm in the Netflix app.
- Is it possible to integrate SEND_KEY options for the Mediabox like the Samsung integration has:

```
service: media_player.play_media
service_data:
  entity_id: media_player.mediabox_next
  media_content_type: send_key
  media_content_id: KEY_CODE (optional keys: https://github.com/roberodin/ha-samsungtv-custom#key-codes)
```
